fix: optimization for multiple schemas and shards
mycodedstuff/db-migration pull request #1
Opened 2024-12-12 07:36 UTC by adiR28

Optimization Track for DB-Migration

2024-12-12 23:23 UTC, mycodedstuff commented on src/Database/Migration.hs
> +  putStrLn $ "task completed"
This can be removed

2024-12-16 08:50 UTC, mycodedstuff commented
As `schemaDiff` function is now working with multiple schemas `groupPredicates` function will see collisions in index names. Make index names schema specific.

2024-12-16 08:50 UTC, mycodedstuff commented on src/Database/Migration.hs
> +  -> IO ()
This function should report the diff it finds to the caller.

2024-12-19 13:31 UTC, mycodedstuff commented on src/Database/Migration/Types.hs
> +  | Diffrence DBDiff
Typo

2024-12-19 13:31 UTC, mycodedstuff commented on src/Database/Migration.hs
> +        False -> return DB_NOT_IN_SYNC
If we return the diff without rendering it, will it cause high memory utilization?

2024-12-19 13:31 UTC, mycodedstuff commented on src/Database/Migration.hs
> +      -- schema = fromMaybe "public" mSchema
Can be removed

2024-12-19 13:31 UTC, mycodedstuff commented on src/Database/Migration/Backend/Postgres/Render.hs
> +                <> quote ind
Is this correct? This should be `oldInd`

2024-12-19 13:31 UTC, mycodedstuff commented on src/Database/Migration/Types.hs
> +  , listDifference :: !Bool
Add about this flag in README and why it can be useful.

2024-12-19 13:31 UTC, mycodedstuff commented on src/Database/Migration/Utils/Beam.hs
> +groupTableHasIndexPredicate predicate acc = do
This can still be a let in expression

2024-12-19 13:31 UTC, mycodedstuff commented on src/Database/Migration/Utils/Common.hs
> +  let indexMap = HM.fromList $ CME.loop(\(acc,ar,count) ->
You can use zip instead of loop.
`zip refArr [0..]`

2024-12-19 13:31 UTC, mycodedstuff commented on stack.yaml
> +  - unicode-data-0.3.1@sha256:ae3a3aca89a32b912ddde7a644c0c04eaf23ee42014c74fe3d6b9aaf36ce7ec9,5481
What's the need of this library?

2024-12-19 13:31 UTC, mycodedstuff commented on stack.yaml
> +  - lockfree-queue-0.2.4@sha256:156e7ccc193fc5d8b43f065e9cd31c3171c79ec25863283d546900d92930846d,2963
What's the need of this library?

2024-12-19 13:38 UTC, adiR28 commented on stack.yaml
> +  - lockfree-queue-0.2.4@sha256:156e7ccc193fc5d8b43f065e9cd31c3171c79ec25863283d546900d92930846d,2963
need for runConc function

2024-12-19 13:40 UTC, adiR28 commented on src/Database/Migration/Backend/Postgres/Render.hs
> +                <> quote ind
checking

2024-12-20 12:58 UTC, adiR28 commented on src/Database/Migration.hs
> +        False -> return DB_NOT_IN_SYNC
yes, sending difference list for sharded database is casuing high memory utilization, around 2.5GB for 1000 shards

2024-12-23 18:33 UTC, mycodedstuff commented on examples/GenerateDDL.hs
> +  !_ <- DBM.schemaDiff conn (testDB (Just schema)) options
Let's print the diff in demo

2025-01-03 18:48 UTC, mycodedstuff requested changes

2025-01-03 18:48 UTC, mycodedstuff commented on README.md
> +Option `listDifference` if set to `True` allows to send the list of differences in haskell code and database. Beware this will cause higher memory utilization if number of shards is large
```suggestion
Option `listDifference` if set to `True` allows to send the return the differences in Haskell and database as DDL queries. Beware this will cause higher memory utilization for higher number of schemas.
```

2025-01-03 18:48 UTC, mycodedstuff commented on README.md
> +Option `listDifference` if set to `True` allows to send the list of differences in haskell code and database. Beware this will cause higher memory utilization if number of shards is large
The issue with memory is it solely dependent on number of schemas? or number of entities?

2025-01-03 18:48 UTC, mycodedstuff commented on README.md
> +If this is `False` library will discard the list and send only `DB_NOT_IN_SYNC` message .
```suggestion
If this is `False` library will discard the list and send only `DB_NOT_IN_SYNC` or `DB_IN_SYNC` message for each schema accordingly.
```

2025-01-06 09:45 UTC, adiR28 commented on README.md
> +Option `listDifference` if set to `True` allows to send the list of differences in haskell code and database. Beware this will cause higher memory utilization if number of shards is large
both

2025-01-06 09:55 UTC, adiR28 commented on README.md
> +Option `listDifference` if set to `True` allows to send the list of differences in haskell code and database. Beware this will cause higher memory utilization if number of shards is large
both

2025-01-27 13:00 UTC, merged